version: '2.2'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: >
      sh -c "gem install jekyll-seo-tag jekyll-sitemap jemoji &&
             jekyll build &&
             jekyll serve --watch --force_polling --verbose"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll